#!/usr/bin/env bash
# This script displays information for the specified subdomains

print_info() {
	local domain=$1
	local subdomain=$2
	ip=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tail -1)
	record_type=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tail -1)
	echo "The subdomain $subdomain is a $record_type record and points to $ip"
}

if [ $# -eq 2 ]
then
	print_info "$1" "$2"
elif [ $# -eq 1 ]
then
	print_info "$1" 'www'
	print_info "$1" 'lb-01'
	print_info "$1" 'web-01'
	print_info "$1" 'web-02'
fi
