#!/usr/bin/env bash
# This script configures Nginx server so that /redirect_me is redirecting to another page
# The redirection is a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"

oldstr="server_name _;"
newstr="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i -e "s|$oldstr|$newstr|" /etc/nginx/sites-enabled/default

sudo service nginx restart
