#!/usr/bin/env bash
# This script configures Nginx server so that /redirect_me is redirecting to another page
# The redirection is a “301 Moved Permanently”

REDIRECT="location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo bash -c "echo 'Hello World!' > /var/www/html/index.html"
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
