#!/usr/bin/env bash
# This script configures Nginx server to have a custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"

oldstr="server_name _;"
newstr="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i -e "s|$oldstr|$newstr|" /etc/nginx/sites-enabled/default

oldstr="@404;"
newstr="@error_404;\n\t}\n\n\tlocation @error_404 {\n\t\tdefault_type text/html;\n\t\treturn 404 \"Ceci n\'est pas une page\n\";"
sudo sed -i -z "s|$oldstr|$newstr|" /etc/nginx/sites-enabled/default

sudo service nginx restart
