#!/usr/bin/env bash
# This script changes the configuration of Nginx, to listen on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -o nginx
