#!/usr/bin/env bash
# This script writes I am alive! to the file /tmp/my_process indefinitely With a sleep 2 in between each iteration

while true
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
