#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, using the while loop + IFS
# make up a story based on it

FILE="/etc/passwd"

while IFS=":" read -r usrname pw uid grpid uidinfo homedir shell
do
	echo "The user $usrname is part of the $grpid gang, \
lives in $homedir and rides $shell. $uid's place is protected by the passcode $pw, \
more info about the user here: $uidinfo"
done < "$FILE"
