#!/usr/bin/env bash
# This script lists the content of the current directory
# only the part of the name after the first dash is displayed

LIST="$(ls)"
for f in $LIST
do
	echo "$f" | cut -d '-' -f2
done
