#!/usr/bin/env bash
# This script installs and configures ufw

sudo apt-get -y install ufw
sudo apt-get -y install ufw

sudo ufw enable

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
