#!/usr/bin/env bash
# This script configures an Ubuntu server
# localhost to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.test
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.test
echo "8.8.8.8 facebook.com" >> ~/hosts.test
cp -f ~/hosts.test /etc/hosts
