#!/usr/bin/env bash
# This Bash script creates an RSA key pair
# Name of the created private key is school
# Number of bits in the created key is 4096
# The created key is protected by the passphrase betty

ssh-keygen -t rsa -f school -b 4096 -N betty

