#!/usr/bin/env bash
# SSH client configuration to use the private key ~/.ssh/school
# SSH client configuration to refuse to authenticate using a password

Host *
    IdentifyFile ~/.ssh/school
    PasswordAuthentication no
